sonar.projectKey=fca_project
sonar.projectName=FCA Project
sonar.projectVersion=1.0

sonar.sources=fca
sonar.language=py

sonar.host.url=http://localhost:9000
sonar.login=sqp_409d451dd5586c98489bedd5723bab6226db9f1e